version: '3.8'

services:
  nginx:
    build: .
    ports:
      - "8080:80"

  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
